#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-lucene-solr
Version  : 8.2.0
Release  : 1
URL      : https://github.com/apache/lucene-solr/archive/releases/lucene-solr/8.2.0.tar.gz
Source0  : https://github.com/apache/lucene-solr/archive/releases/lucene-solr/8.2.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: Jinja2
Requires: PyYAML
Requires: six
BuildRequires : Jinja2
BuildRequires : PyYAML
BuildRequires : apache-ant
BuildRequires : buildreq-mvn
BuildRequires : six

%description
http://www.splitbrain.org/projects/file_icons
Released to the Public Domain
Free to use. Provided as is. No warranties.

%prep
%setup -q -n lucene-solr-releases-lucene-solr-8.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export ANT_HOME=/usr/share/ant
ant -d -v
%install


%files
%defattr(-,root,root,-)
